-- 1. Cria roles
INSERT INTO ROLE (ID, NOME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, NOME) VALUES (2, 'ROLE_USER');
INSERT INTO ROLE (ID, NOME) VALUES (3,'ROLE_SECRETARIA');

-- 2. Cria usuários com IDs fixos
INSERT INTO USUARIO (ID, LOGIN, SENHA) VALUES (1, 'admin', '$2a$10$jCCXk2Nz0nKJfmx4qAbJx..epDzyCp8wVzsIqC1bXPIO6zMfoKuHa');
INSERT INTO USUARIO (ID, LOGIN, SENHA) VALUES (2, 'user', '$2a$10$euZ9Mx01uHTGLaQQukZVFucMVm2EVW/eVHNSSob7g9p.bQ/G4Z4U6');

-- 3. Relaciona usuário com role
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROLE_ID) VALUES (1, 1); -- admin -> ROLE_ADMIN
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROLE_ID) VALUES (2, 2); -- user -> ROLE_USER
-- Apaga todos os usuários exceto o admin (opcional)
ALTER TABLE usuario ALTER COLUMN id RESTART WITH 3;